export function canonicalFixture() {
  return {
    period_start: "2026-08-16",
    period_end: "2026-08-22",
    category_breakdown: [{ category: "Coding", total_seconds: 999999 }],
    focus_semantics: {
      policy_version: "deep-focus-v2",
      construct_label: "Observable sustained-work proxy",
      proxy_disclaimer: "This does not measure subjective flow.",
      focused_threshold_seconds: 600,
      deep_threshold_seconds: 1500,
      extended_threshold_seconds: 3000,
      sensor_grace_seconds: 60,
      browsing_distraction_min_seconds: 120,
      focus_eligible_seconds: 6000,
      explicit_theme_seconds: 4800,
      explicit_theme_coverage_pct: 80,
      deep_focus_seconds: 3100,
      deep_focus_sessions: 2,
      longest_focus_seconds: 1900,
      theme_switches: 3,
      explicit_theme_switches_per_labelled_focus_hour: 2.3,
      fragmentation_pct: 18.5,
      resume_events: 2,
      average_resume_seconds: 210,
      distraction_events: 1,
      distraction_seconds: 150,
      context_work_seconds: 2400,
      context_category_mix: [
        { category: "Planning", seconds: 600 },
        { category: "Meeting", seconds: 600 },
        { category: "Administration", seconds: 300 },
        { category: "Sales", seconds: 300 },
        { category: "Research", seconds: 300 },
        { category: "Design", seconds: 300 },
      ],
    },
  };
}
